version: '3.9'

services:
  gemma:
    image: ollama/ollama
    container_name: gemma-3
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      #- OLLAMA_NUM_PARALLEL=4 for several request at the same time
    ports:
      - 11437:11434  # Map host 11437 to container 11434
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/bash", "-c", "\
      ollama serve & \
      sleep 5 && \
      ollama pull gemma3:1b && \
      wait"]

# docker compose -f compose.gemma-3.yaml up