services:
  db:
    container_name: ${POSTGRES_DB}
    image: postgres:18.1
    env_file: ../../../../.env
    environment:
      APP_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./utils/db-data:/var/lib/postgres/data
      - ./utils/log-data:/var/lib/postgres/logs
      - ../utils/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "postgres_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db-data:
  log-data: